# Model Parameters
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 3,
    block_id: 9,
    source_path: "data/matrix_city/aerial/train/block_9",
    pretrain_path: "output/org_mc_aerial_block9/point_cloud/iteration_30000",
    model_path: "",
    images: "images",
    block_dim: [4, 4, 1],
    aabb: [-5, 0, 5, 4],
    opacity_threshold: 25000,
    resolution: -1,
    white_background: False,
    data_device: "cuda",
    eval: False,
    logger_config: {
        logger: "wandb",
        name: "block_mc_aerial_block9_cell9_opac25",
        project: "LargeGS"
    }
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python:  False,
    compute_cov3D_python:  False,
    pre_load: True,
    debug:  False
}


# Optimization Parameters
optim_params: {
    iterations: 30_000,
    position_lr_init: 0.00004,
    position_lr_final: 0.0000016,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 30_000,
    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.005,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 100,
    opacity_reset_interval: 3000,
    densify_from_iter: 500,
    densify_until_iter: 15_000,
    densify_grad_threshold: 0.0002
}


