# Model Parameters
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 3,
    source_path: "data/mill19/rubble-pixsfm/train",
    partition_name: "block_rubble_all_lr_c9_loss_12_r4_simple_selection",
    model_path: "",
    images: "images",
    block_dim: [3, 1, 3],
    aabb: [-50, -100, -135, 50, 300, -5],
    filter_mode: "loss",
    opacity_threshold: 0.12,
    resolution: 4,
    white_background: False,
    data_device: "cuda",
    eval: False,
    logger_config: {
        logger: "wandb",
        name: "block_rubble_all_lr_c9_loss_12_r4_simple_selection_coarse",
        project: "LargeGS"
    }
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python:  False,
    compute_cov3D_python:  False,
    pre_load: False,
    debug:  False
}


# Optimization Parameters
optim_params: {
    iterations: 60_000,
    position_lr_init: 0.00016,
    position_lr_final: 0.0000016,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 30_000,
    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.005,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 200,
    opacity_reset_interval: 6000,
    densify_from_iter: 1000,
    densify_until_iter: 30_000,
    densify_grad_threshold: 0.0002
}


