# Model Parameters
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 3,
    source_path: "data/matrix_city/aerial/train/block_all",
    partition_name: "block_mc_aerial_block_all_lr_c36_loss_8_num_10w",
    pretrain_path: "output/org_mc_aerial_block_all_lr2/point_cloud/iteration_30000",
    model_path: "",
    images: "images",
    block_dim: [6, 6, 1],
    aabb: [-3.5, -4, 4.5, 2],
    filter_mode: "loss",
    opacity_threshold: 0.08,
    num_threshold: 100000,
    resolution: -1,
    white_background: False,
    data_device: "cuda",
    eval: True,
    logger_config: {
        logger: "wandb",
        name: "block_mc_aerial_block_all_lr_c36_loss_8_num_10w_lr2_ssim3_ohem-scratch",
        project: "LargeGS"
    }
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python:  False,
    compute_cov3D_python:  False,
    pre_load: False,
    debug:  False
}


# Optimization Parameters
optim_params: {
    iterations: 30_000,
    position_lr_init: 0.000064,
    position_lr_final: 0.00000064,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 30_000,
    feature_lr: 0.00125,
    opacity_lr: 0.025,
    scaling_lr: 0.004,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.3,
    densification_interval: 200,
    opacity_reset_interval: 3000,
    densify_from_iter: 500,
    densify_until_iter: 15_000,
    densify_grad_threshold: 0.0002,
    ohem: True
}


