# Model Parameters
model_params: {
    name: "GaussianModel",
    sh_degree: 3,
    source_path: "",
    model_path: "",
    pretrain_path: "output/fuse_ue_aerial_20_blockFcam_7k/point_cloud/iteration_7000",
    test_source: "data/UE-collected/street/block2_5_cam",
    sub_paths: ["config/org_ue_aerial_20_block1cam.yaml", 
                "config/org_ue_aerial_20_block2cam.yaml", 
                "config/org_ue_street_5_block2cam.yaml"],
    images: "images",
    resolution: -1,
    white_background: False,
    data_device: "cuda",
    eval: True,
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python:  False,
    compute_cov3D_python:  False,
    debug:  False
}


# Optimization Parameters
optim_params: {
    iterations: 7_000,
    position_lr_init: 0.00016,
    position_lr_final: 0.0000016,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 7_000,
    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.005,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 100,
    opacity_reset_interval: 3000,
    densify_from_iter: 500,
    densify_until_iter: 15_000,
    densify_grad_threshold: 0.0002
}


