# Model Parameters
model_params: {
    model_config: {
        name: "GaussianModelVox",
        kwargs: {
            xyz_range: [-11, -4, 0, 11, 7, 3]
        }
    },
    sh_degree: 3,
    source_path: "data/matrix_city/aerial/train/block_9",
    model_path: "",
    images: "images",
    data_device: "cuda",
    resolution: -1,
    white_background: False,
    eval: False,
    logger_config: {
        logger: "wandb",
        name: "lod_mc_aerial_block9_v3_normx2_act",
        project: "LargeGS"
    }
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python:  False,
    compute_cov3D_python:  False,
    pre_load: True,
    blur_level: 0,
    debug:  False
}


# Optimization Parameters
optim_params: {
    iterations: 30_000,
    position_lr_init: 0.00008,
    position_lr_final: 0.0000008,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 30_000,
    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.0025,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 100,
    opacity_reset_interval: 3000,
    densify_from_iter: 500,
    densify_until_iter: 15_000,
    densify_grad_threshold: 0.0002
}


