# Model Parameters
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 3,
    source_path: "data/matrix_city/aerial/train/block_all",
    partition_name: "mc_aerial_c36",
    pretrain_path: "output/mc_aerial_coarse/point_cloud/iteration_30000",
    model_path: "",
    images: "images",
    block_dim: [6, 6, 1],
    aabb: [-3.5, -4, -10, 4.5, 2, 10],
    ssim_threshold: 0.05,
    resolution: -1,
    white_background: False,
    data_device: "cuda",
    eval: False,
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python:  False,
    compute_cov3D_python:  False,
    debug:  False
}


# Optimization Parameters
optim_params: {
    iterations: 30_000,
    position_lr_init: 0.000064,
    position_lr_final: 0.00000064,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 30_000,
    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.004,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 200,
    opacity_reset_interval: 3000,
    densify_from_iter: 500,
    densify_until_iter: 15_000,
    densify_grad_threshold: 0.0002
}


