# Model Parameters
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 3,
    source_path: "data/matrix_city/street/train/block_A",
    model_path: "",
    images: "images",
    resolution: -1,
    white_background: False,
    add_background_sphere: True,
    background_sphere_points: 100_000,
    background_sphere_radius: 2.2,
    data_device: "cuda",
    eval: False,
    logger_config: {
        logger: "wandb",
        name: "org_mc_street_block_all_0lr",
        project: "LargeGS"
    }
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python:  False,
    compute_cov3D_python:  False,
    debug:  False
}


# Optimization Parameters
optim_params: {
    iterations: 30_000,
    position_lr_init: 0,
    position_lr_final: 0,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 30_000,
    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.005,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 20_000,
    opacity_reset_interval: 20_000,
    densify_from_iter: 250,
    densify_until_iter: 15_000,
    densify_grad_threshold: 0.0002
}


